"""changing models

Revision ID: 77883643b2ef
Revises: 700a8af61e1e
Create Date: 2024-07-10 10:16:57.418371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77883643b2ef'
down_revision = '700a8af61e1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('surveys')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_questions_survey_id_surveys', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_questions_quiz_id_quizzes'), 'quizzes', ['quiz_id'], ['id'])
        batch_op.drop_column('survey_id')

    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_responses_survey_id_surveys', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_responses_quiz_id_quizzes'), 'quizzes', ['quiz_id'], ['id'])
        batch_op.drop_column('survey_id')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_reviews_survey_id_surveys', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_quiz_id_quizzes'), 'quizzes', ['quiz_id'], ['id'])
        batch_op.drop_column('survey_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('survey_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_reviews_quiz_id_quizzes'), type_='foreignkey')
        batch_op.create_foreign_key('fk_reviews_survey_id_surveys', 'surveys', ['survey_id'], ['id'])
        batch_op.drop_column('quiz_id')

    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('survey_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_responses_quiz_id_quizzes'), type_='foreignkey')
        batch_op.create_foreign_key('fk_responses_survey_id_surveys', 'surveys', ['survey_id'], ['id'])
        batch_op.drop_column('quiz_id')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('survey_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_questions_quiz_id_quizzes'), type_='foreignkey')
        batch_op.create_foreign_key('fk_questions_survey_id_surveys', 'surveys', ['survey_id'], ['id'])
        batch_op.drop_column('quiz_id')

    op.create_table('surveys',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('quizzes')
    # ### end Alembic commands ###
