"""adds image_url

Revision ID: 827e568617de
Revises: c600abda3f1b
Create Date: 2024-07-14 20:32:32.927485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827e568617de'
down_revision = 'c600abda3f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
