"""add serialize rules

Revision ID: b4e4a6f96bd8
Revises: 54d4fa1ba5bc
Create Date: 2024-07-09 11:26:24.529797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4e4a6f96bd8'
down_revision = '54d4fa1ba5bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('choice_1',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('choice_2',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('choice_3',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('choice_4',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('choice_4',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)
        batch_op.alter_column('choice_3',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)
        batch_op.alter_column('choice_2',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)
        batch_op.alter_column('choice_1',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)

    # ### end Alembic commands ###
